- prototypes/alienvault.yml
- prototypes/anomali.yml
- prototypes/auscert.yml
- prototypes/autofocus.yml
- prototypes/aws.yml
- prototypes/azure.yml
- prototypes/blocklist_de.yml
- prototypes/bruteforceblocker.yml
- prototypes/dshield.yml
- prototypes/google.yml
- prototypes/hailataxii.yml
- prototypes/malwaredomainlist.yml
- prototypes/office365.yml
- prototypes/openbl.yml
- prototypes/openphish.yml
- prototypes/proofpoint.yml
- prototypes/ransomwaretracker.yml
- prototypes/recordedfuture.yml
- prototypes/spamhaus.yml
- prototypes/sslabusech.yml
- prototypes/stdlib.yml
- prototypes/themediatrust.yml
- prototypes/tor.yml
- prototypes/virbl.yml
- prototypes/zeustracker.yml
Changed author of Prototypes provided by MineMeld core team from Palo Alto Networks to MineMeld Core Team.
> switched from Palo Alto Networks to MineMeld Core Team

- prototypes/ETOpen.yml
- prototypes/feodotracker.yml
Added new ET prototype from Greg Roehl
Added Feodo Tracker prototypes
Commit By Luigi Mori (lmori@paloaltonetworks.com)
> Added new prototypes

- prototypes/anomali.yml
- prototypes/autofocus.yml
- prototypes/aws.yml
- prototypes/badips.yml
- prototypes/binarydefense.yml
- prototypes/office365.yml
- prototypes/ransomwaretracker.yml
- prototypes/themediatrust.yml
Moved some prototypes to STABLE and fix PaloAltoNetworks/minemeld-node-prototypes#12
> Moved some prototypes to STABLE and fix #12

- prototypes/threatq.yml
> Added ThreatQ prototypes

- prototypes/ETOpen.yml
Fixes PaloAltoNetworks/minemeld-node-prototypes#18
> Added url and ignore_regex

- prototypes/bambenekconsulting.yml
Added prototype library for bambanekconsulting feeds.
> Added bambanekconsulting feeds

- prototypes/cif.yml
> Added prototype for the new CIF Miner

- prototypes/virustotal.yml
Added virustotal prototype library. Only prototype currently is the notifications prototype.
> Added virustotal library

- prototypes/phishme.yml
> Added prototype for phishme.Intelligence

- prototypes/hailataxii.yml
Added several new [Hail a TAXII](http://hailataxii.com/) prototypes:
* Abuse_ch
* CyberCrime_Tracker
* EmergingThreats_rules
* MalwareDomainList_Hostlist
* blutmagie_de_torExits
* dataForLast_7daysOnly
* dshield_BlockList
> additional prototypes for HailATaxii

- README.md
Signed-off-by: Dan Dye <ddye@soltra.com>
> add link to wiki in ReadMe.md

- prototypes/stdlib.yml
For PaloAltoNetworks/minemeld-core#80
> Added DAG non persistent prototype

- prototypes/stdlib.yml
> Fixes wrong description in feedHCGreen

- prototypes/office365.yml
Prototype for PaloAltoNetworks/minemeld-core#104
> Adds prototype for O365 any

- prototypes/stdlib.yml
> Aggregators for new indicator types

- prototypes/stdlib.yml
> Adds aggregator for new process command_line

- prototypes/minemeld.yml
> Adds minemeld.yml library

- prototypes/blutmagie.yml
> Adds blutmagie Tor feeds

- prototypes/dhs.yml
Created a DHS prototype for AIS and CISCP
> DHS prototype

- prototypes/office365.yml
> Adds office365.Teams prototype

- prototypes/aws.yml
> Adds aws.S3 prototype

- prototypes/dhs.yml
> Activate lower_timestamp_precision flag on DHS prototypes

- prototypes/recordedfuture.yml
added the necessary code for the new DomainRiskList class to be referenced as an input mining node
> added DomainRiskList prototype

- prototypes/recordedfuture.yml
Luigi Mori <lmori@paloaltonetworks.com>
> Fixed RF description and author

- prototypes/itcertpa.yml
See PR #53 same content from @gmellini but with clean commit history.
> Clean PR#53 commit log

- prototypes/office365-dod.yml
- prototypes/office365-usdefense.yml
> Adds prototypes for O365 US Government endpoints

- prototypes/stdlib.yml
> Adds Miner for localdb

- prototypes/blocklist_net_ua.yml
- prototypes/recordedfuture.yml
> Fixed RF Domain list and added blocklist_net_ua

- prototypes/surbl.yml
Prototypes for SURBL two and three level reputation lists
> Prototypes for SURBL Reputation Lists

- prototypes/greensnow.yml
> Added miner for GreenSnow

- prototypes/nothink.yml
> Added miner for NoThink.org

- prototypes/malc0de.yml
Added miner for malc0de DNS Sinkhole
> Added miner for malc0de

- prototypes/urlhaus.yml
Add Miner Prototype for URLhaus Service
> Add Miner Prototype for URLhaus Service

- prototypes/o365-api.yml
See PaloAltoNetworks/minemeld-core#267
> O365 API Prototypes

- prototypes/libraesva.yml
There was a problem in the indentation of the configuration
> Fixed indenting config

- prototypes/o365-api.yml
> Changed O365 prototypes

- prototypes/stdlib.yml
> Adds email aggregator

- prototypes/o365-api.yml
- prototypes/office365-dod.yml
- prototypes/office365-usdefense.yml
- prototypes/office365.yml
> O365 API improvements

- prototypes/feodotracker.yml
> Fixes #95 and adds new prototypes to feodotracker for hashes

- prototypes/spamhaus.yml
> Implements #94

- prototypes/azure.yml
Implements PaloAltoNetworks/minemeld-core#311
> Implements PaloAltoNetworks/minemeld-core#311

- prototypes/sslabusech.yml
> Fix SSL Abuse CH URLs

- prototypes/stix2.yml
- add prototype for generic STIX2 miner
- add prototype for pre-configured Unit42 playbook STIX2/TAXII2 feed
> Implement STIX2 miner

- prototypes/recordedfuture.yml
@jtschichold : As per your guidance, I have marked old miners as deprecated and not changed the author's name. Also added a new line at the end. I have implemented all the changes suggested in #111 
Thanks,
Shaishav Shah
> Recommended Changes New Miner Prototype

- prototypes/ransomwaretracker.yml
Deprecating Ransomwaretracker.
Signed-off-by: Luigi Mori <l@isidora.org>
> Implements #113

- prototypes/blutmagie.yml
- prototypes/zeustracker.yml
Deprecating Zeus Abuse CH and Blutmagie
Signed-off-by: Luigi Mori <l@isidora.org>
> Implements #106 and #91

- prototypes/azure.yml
- prototypes/stdlib.yml
Adds new prototype for IPv4 list merge and deprecates soon to be discontinued Azure XML feed
Signed-off-by: Luigi Mori <l@isidora.org>
> Improvements for Azure Cloud IPs

- prototypes/bambenekconsulting.yml
> Adds support for new Bambenek class

- prototypes/cofense.yml
Signed-off-by: Luigi Mori <l@isidora.org>
> Renamed PhishMe into Cofense

- prototypes/cofense.yml
Adds support for cofense triage api
> Adding cofense triage prototype
